import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/header'
import OutboundSearchBar from '../components/searchbars/OutboundSearchBar'
import DestinationSearchBar from '../components/searchbars/DestinationSearchBar'
import DepartDate from '../components/searchbars/DepartDate'
import ArrivalDate from '../components/searchbars/ArrivalDate'
import SearchButton from '../components/button/searchButton'

import styles from '../styles/Home.module.css'
import Logo from '../components/logo/Logo'

//React page component for the homepage
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header/> */}
      <Logo/>
      <div className="rounded-lg shadow-lg border-solid border-2 border-inherit box-border content-center absolute inset-x-0 ml-80 mr-80 left-12 right-12 h-40 w-min">
        <div className="flex flex-row justify-center gap-x-2.5 mx-10 mt-5">
          <OutboundSearchBar/>
          <DestinationSearchBar/>
          <DepartDate/>
          <ArrivalDate/>
          <SearchButton/>
        </div>
      </div>

  </div>
  );
}
