import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../components/header/header'
import OutboundSearchBar from '../components/searchbars/OutboundSearchBar'
import DestinationSearchBar from '../components/searchbars/DestinationSearchBar'
import DepartDate from '../components/searchbars/DepartDate'
import ArrivalDate from '../components/searchbars/ArrivalDate'
import SearchButton from '../components/button/searchButton'
import TripButton from '../components/button/tripButton'
import { UseUser } from '@auth0/nextjs-auth0/dist/frontend/use-user'

import styles from '../styles/Home.module.css'
import Logo from '../components/logo/Logo'

import type { NextPage } from 'next'
import LoginForm from '../components/loginForm/login-form'
//React page component for the homepage
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href="/LoginPage"
          className="px-6 py-3 text-blue-100 no-underline bg-navy rounded-lg hover:bg-blue-600 hover:underline hover:text-blue-200 absolute top-3 right-3">Log In
          </a>
      <Logo/>
      <div className="rounded-lg shadow-lg border-solid border-2 border-inherit box-border content-center absolute inset-x-0 ml-80 mr-80 left-12 right-12 h-40 w-min -mt-9">
        <div className="flex flex-row justify-center gap-x-2.5 mx-10 mt-4">
          <OutboundSearchBar/>
          <DestinationSearchBar/>
          <DepartDate/>
          <ArrivalDate/>
          <SearchButton/>
        </div>
        <div className="flex flex-row justify-left gap-x-2.5 mx-10">
          <TripButton>
          </TripButton>
          <label className="text-black text-base font-semibold block relative text-right ml-0.5 mt-6">
            Roundtrip
          </label>
          <TripButton>
          </TripButton>
          <label className="text-black text-base font-semibold block relative text-right ml-0.5 mt-6">
            One-Way
          </label>
          <TripButton>
          </TripButton>
          <label className="text-black text-base font-semibold block relative text-right ml-0.5 mt-6">
            Multi-City
          </label>
        </div>
          
      </div>
  </div>
  
  );
}
