import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../components/header/header'
import OutboundSearchBar from '../components/searchbars/OutboundSearchBar'
import DestinationSearchBar from '../components/searchbars/DestinationSearchBar'
import DepartDate from '../components/searchbars/DepartDate'
import ArrivalDate from '../components/searchbars/ArrivalDate'
import SearchButton from '../components/button/searchButton'
import TripButton from '../components/button/tripButton'
import { UseUser } from '@auth0/nextjs-auth0/dist/frontend/use-user'
import Budget from '../components/budget/budget'
import Activities from '../components/activities/activities'

import styles from '../styles/Home.module.css'
import Logo from '../components/logo/Logo'

import type { NextPage } from 'next'
import LoginForm from '../components/loginForm/login-form'
//React page component for the homepage
export default function Home() {  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute top-0 right-0 font-semibold text-white mr-6 mt-2.5 text-lg rounded-lg hover:text-xl hover:underline">
            <Image className = "relative inline-block mr-1.5 -mt-0.5" src = "/login.svg" alt="..." width={24} height={24}/>
            <Link href="/LoginPage" className="no-underline text-white">login</Link>
      </div>

      <Logo/>
      <div className="rounded-lg shadow-lg border-solid border-2 border-inherit box-border content-center absolute inset-x-0 ml-80 mr-80 left-12 right-12 h-40 w-min -mt-9">
        <div className="flex flex-row justify-center gap-x-2.5 mx-10 mt-4">
          <OutboundSearchBar/>
          <DestinationSearchBar/>
          <DepartDate/>
          <ArrivalDate/>
          <SearchButton/>
        </div>
        <div className="flex flex-row justify-left gap-x-2.5 mx-10">
          <TripButton>
          </TripButton>
          </div>
      </div>
      <h2 className="text-marine text-center text-3xl font-semibold mt-52">Personalize Your Suggestions.</h2>
      
      <Budget></Budget>

      <Activities></Activities>
 
    </div>
  );
}
